RULESET_VERSION = "1.1"
MAX_EMBEDDED_URLS_ANALYZED = 3
MAX_URL_CANDIDATES = 10

PUNYCODE_HOSTNAME_SCORE = 15
NONSTANDARD_PORT_SCORE = 10
EXCESSIVE_HOSTNAME_LABEL_SCORE = 10
EXCESSIVE_HOSTNAME_LABEL_THRESHOLD = 5
STANDARD_PORT_BY_SCHEME = {
    "http": 80,
    "https": 443,
}

STRUCTURED_TEXT_PREVIEW_MAX_LENGTH = 100
WIFI_SSID_PREVIEW_MAX_LENGTH = 50
