RULESET_VERSION = "1.1"
MAX_EMBEDDED_URLS_ANALYZED = 3
MAX_URL_CANDIDATES = 10

PUNYCODE_HOSTNAME_SCORE = 15
NONSTANDARD_PORT_SCORE = 10
EXCESSIVE_HOSTNAME_LABEL_SCORE = 10
EXCESSIVE_HOSTNAME_LABEL_THRESHOLD = 5
STANDARD_PORT_BY_SCHEME = {
    "http": 80,
    "https": 443,
}

STRUCTURED_TEXT_PREVIEW_MAX_LENGTH = 100
WIFI_SSID_PREVIEW_MAX_LENGTH = 50

NON_URL_SCORING_VERSION = "2.0"
DANGEROUS_SCHEME_SCORE = 70
SOCIAL_ENGINEERING_CATEGORY_SCORES = {
    "credential_request": 20,
    "payment_request": 25,
    "urgency": 10,
    "impersonation_support": 15,
    "prize_reward": 10,
    "personal_info_request": 20,
}
SCORE_URGENCY_WITH_CREDENTIAL_OR_PERSONAL_INFO = 15
SCORE_URGENCY_WITH_PAYMENT = 20
SCORE_IMPERSONATION_WITH_SENSITIVE_REQUEST = 15
SCORE_PRIZE_WITH_PERSONAL_INFO = 10
SCORE_MULTI_SOCIAL_WITH_EXPLICIT_URL = 10
SCORE_LONG_CONTENT_WITH_MULTI_SOCIAL = 5
